### ISSUE TITLE
Not able to read few cards

### ISSUE THREAD

**Issue by ghost** [paulvha/rfid-rc522#3]
Some set of cards i am not able to read, i was using aurdino previously, with which i was able to read all cards. Can you look over into if there is any issue in the code.

**Comment by paulvha** [comment]
I’ll look at it today. There were some issues when I worked on it, which I solved,  and need to refresh my memory.

Van: evlmkudu [mailto:notifications@github.com]
Verzonden: maandag 24 juli 2017 14:34
Aan: paulvha/rfid-rc522 <rfid-rc522@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [paulvha/rfid-rc522] Not able to read few cards (#3)


Some set of cards i am not able to read, i was using aurdino previously, with which i was able to read all cards. Can you look over into if there is any issue in the code.

**Comment by ghost** [comment]
okay, can you commit the latest changes, so that i can see whether its working?

**Comment by paulvha** [comment]
A couple of points that can impact:
1. people reported in the past that they had issues with longer cables or if the connection was not solid enough on the connector of the RC522. 

2. You could try to LOWER the SPI speed by decreasing the SPI speed value in the configuration file. The current value is 1.000 (given about 1Mhz for transfer). Decreasing the value to 100 will make it about 100HZ. (close to the transfer speed between the card and reader).  Given that the clock-pulse is longer, it might make it more stable.

3. it is documented in the data sheet that : the size and tuning of the antenna and the power supply voltage have an important impact on the achievable operating distance. Some have tried to make a better antenna, but that is a hell of a job. As the Arduino runs on 5 volt it might have enough impact. You can try to connect to the 5V supply instead of 3.3V on the raspberry. It works as well with me, but I will increase the voltage output on the MOSI connection to a level to 4.5V and that it could hurt the raspberry Pi if done for longer time. BUT you could try to see whether the cards are read better for short test. (on your own risk of course, but with me a it worked) It that works better you need to make a voltage drop with 2 resistors to max 3.3V.

4. I have installed the software and checked the code. it works, but now more than a year  later it is not to the quality level I am coding today. I will work to update in the coming month, but that will not make it more sensitive.

5. One other aspect you could try, in the file rc522.c, PcdReset routine, it writes a value of 0x68 to the RFCfgreg register. That sets a gain of  43db for the receiver, you could try to change that to 0x78 to create a gain of 48db (making the receiver more sensitive.)

**Comment by ghost** [comment]
I have tried all the options, i have soldered the wires, changed SPI speed, increased the gain  nothing has worked out and in aurdino i was connecting to 3.3v pin, on pi when i try to connect to 5v the receiver is not responding. I still worry why only for few cards its working and not for others, when all of them are of same kind.

**Comment by paulvha** [comment]
Weird.

Couple of questions :
Are you sure they worked on the Arduino all the time?
Which card types do you use ?
Is SPI interface disabled raspi-config ?
Which version of BCM2835 are you using ?
To what pins is the RC522 connected on the rasp?
start rc522 without options, it will show are request for a card. What happens if you hold the card before the reader ? Will it detect the card and show the serial number?
If this detections works, whatelse do you see failing ?

Depending on you answers I can try to make a version with special debug options to try to understand where it fails.

Regards,
Paul

Van: evlmkudu [mailto:notifications@github.com]
Verzonden: woensdag 26 juli 2017 07:00
Aan: paulvha/rfid-rc522 <rfid-rc522@noreply.github.com>
CC: paulvha <paulvha@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [paulvha/rfid-rc522] Not able to read few cards (#3)


I have tried all the options, i have soldered the wires, changed SPI speed, increased the gain nothing has worked out and in aurdino i was connecting to 3.3v pin, on pi when i try to connect to 5v the receiver is not responding. I still worry why only for few cards its working and not for others, when all of them are of same kind.

**Comment by ghost** [comment]
Yes they are working on the arduino all time, i just want to replace arduino with pi
card type=4400
BCM2385 - 1.35
SPI interface disabled in raspi-config
Name | Pin  | Pin name
SDA   | 24   | GPIO8
SCK   | 23   | GPIO11
MOSI | 19   | GPIO10
MISO | 21   | GPIO9
GND  | Any | Any Ground
RST   | 22   | GPIO25
3.3V   | 1    | 3V3

i am able to read type and s/n for  few cards, for other cards when i place it on the reader nothing is getting printed.

**Comment by paulvha** [comment]
sounds all good & correct.  
I have tried different 4400 cards (new and old) and they all work without a problem. Can you try to update BCM2835 (downloadable from a link on http://www.airspayce.com/mikem/bcm2835/index.html) the latest version is 1.52. Will try to make a special debug function as well.

**Comment by paulvha** [comment]
Which software did you use for the arduino. Do you have the link so i can compare the reset or init.

Regards
Paul


Outlook voor Android<https://aka.ms/ghei36> downloaden

________________________________

**Comment by ghost** [comment]
https://www.raspberrypi.org/downloads/raspbian/  in this link i am using "Raspbian Jessie with desktop"

**Comment by ghost** [comment]
this is not the problem with hardware, i have just checked python code, it's working fine with all the cards in raspberrypi, can please look into the code once again.

**Comment by ghost** [comment]
actually i am checking other c code where i am not able to read any type:4400, where exactly configuration changes for this type  of cards?

**Comment by paulvha** [comment]
which Python code did you use . I can check what the difference might be? for the actual reading of the card is the same up to the point of just getting the type and serial number.

**Comment by ghost** [comment]
https://github.com/mxgxw/MFRC522-python this the code i was referrring

**Comment by paulvha** [comment]
it looks to me on this moment that either it is has to do with the init or with the anticollision code. I checked the init code and compared to a number of arduino and Python codes on GitHub. The difference is everytime that  they do NOT change the default value in GsnReg, nor in CWGsCfgReg. The receiver RFCfgReg is neither updated. Try to comment-out the WriteRawRC() calls for those 3 in the RC522.c , PcdReset function. expect them to be near lines 348, 354 and 360. let me know whether that makes a difference (I tried it and had the same good card readings). 
Also move the line 302 (SetBitMask(TxControlReg,0x03) to the end (just before line 364: return TAG_OK). The other init code only put the antenna back on at the end of init

**Comment by ghost** [comment]
tried that option too, no change in response, can we have a google hangout meeting to fix this?

**Comment by paulvha** [comment]
where are you based?

**Comment by ghost** [comment]
i am from india

**Comment by paulvha** [comment]
Netherlands for me. Drop me a mail on paulvha@hotmail.com. I am currently looking at the anticollision and create a special debug version.

**Comment by ghost** [comment]
what is your preferable time? so that i can schedule a meeting.

**Comment by paulvha** [comment]
if is nearly 11.50AM here now. Not sure what is for you ? but I could do in the coming 4 hours.

**Comment by paulvha** [comment]
try this version (it will generate debug messages) about the request and select phase
[rctst.tar.gz](https://github.com/paulvha/rfid-rc522/files/1179504/rctst.tar.gz)

**Comment by ghost** [comment]
when i check with new code, i am able to see in debug its getting collicion tag:88, for the cards which are not detected previously and for the cards which were detecting its giving card found and gets terminated

**Comment by ghost** [comment]
i have also scheduled a call in another half an hour, hope you got the meeting invitation

**Comment by paulvha** [comment]
yes.

**Comment by ghost** [comment]
i have sent a snapshot, can you look over it?

**Comment by ghost** [comment]
please join the meeting

**Comment by paulvha** [comment]
a newer version for test. can you try and share the outcome
[rctst2.tar.gz](https://github.com/paulvha/rfid-rc522/files/1179775/rctst2.tar.gz)

**Comment by ghost** [comment]
no, i still see that length of the message 0 after collision tag:88. i have shared the screen short to you. Please have a look at it.

**Comment by paulvha** [comment]
new version for test
[rctst3.tar.gz](https://github.com/paulvha/rfid-rc522/files/1179896/rctst3.tar.gz)

**Comment by ghost** [comment]
now i think you are almost closer to the error point i am getting first 3 bytes and after that the data is incorrect.

**Comment by ghost** [comment]
Thanks a lot for the support, now i am able to read all the cards, may be after complete work around you can commit final version for all others.
